### PR TITLE
Update to 0.2.4

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender.

**Comment by ccordoba12** [comment]
@ocefpaf, how can I update this recipe to use conda-build 3?

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender.

**Comment by mariusvniekerk** [comment]
3.7 is being managed by the regro bot to ensure that your dependencies have been built already

**Comment by ccordoba12** [comment]
@mariusvniekerk, thanks for chiming in. So we have to wait until regro comes to this repo? Or can we call it automatically?

**Comment by ccordoba12** [comment]
I say it because I took a look at our deps, and all of them already have Python 3.7 packages.

**Comment by mariusvniekerk** [comment]
So the easy way to force this is to add `max_py_ver: '37'` to your `conda-smithy.yml`.  And then just rerender

**Comment by mariusvniekerk** [comment]
This seems to not have rerendered properly?

**Comment by ccordoba12** [comment]
> This seems to not have rerendered properly?

Yeah, but I don't know why.

**Comment by mariusvniekerk** [comment]
I'd recommend trying to do the render locally using conda-smithy yourself

**Comment by ccordoba12** [comment]
Ok, will do. Thanks @mariusvniekerk!

**Comment by ccordoba12** [comment]
@mariusvniekerk, I don't know if it was you who rerender the repo directly, but thanks a lot for that!

**Comment by mariusvniekerk** [comment]
that was the bot waking up for *some* reason

**Comment by ccordoba12** [comment]
@mariusvniekerk, could you take a look at the Circle and Travls latest logs? I don't understand the source of the error we're getting there.

**Pull request merged**
